### PR TITLE
show duplicate gadgets

### PR DESCRIPTION
**Pull request by cottow**
Deleted the code that makes sure only unique gadgets are shown. This gives a better sense of gadgetry in the binary.

### CODE REVIEW

**Comment by blasty** [comment]
It was originally a feature, but yes I can see the need for this. Should probably become a cli option of some kind. Will sleep on it. ;)

**Comment by cottow** [comment]
I've made it a cli option, and added an option to specify what section to search in. You might want to have a look at disas_str line 79-81, I didn't quite get what optparse was being used for there but made it work nonetheless. So fingers crossed :-)

**Comment by cottow** [comment]
Also, removed the option to only search in executable sections, as the loader apparently maps more sections into executable pages than just those marked as executable. For instance, .plt is not marked as executable (flag 0x4) but is obviously still in executable memory.

**Comment by blasty** [comment]
@cottow: Thanks for this (useful) contribution! Verified and working nicely, merged to master. :+1:

**Pull request merged**
